In [1]:
import pandas as pd

# 1. Cargar el dataset
# Nota: Pandas necesita el motor 'pyarrow' o 'fastparquet' para leer este formato.
# Si te da error, instala en tu terminal: pip install pyarrow
ruta_archivo = '../data/processed/dataset_completo.parquet'
df_m30 = pd.read_parquet(ruta_archivo)

# 2. Inspección de tipos de datos y memoria
print("--- 1. Información General del Dataset ---")
df_m30.info()
print("\n" + "="*50 + "\n")

# 3. Verificación visual del inicio y fin de la serie
print("--- 2. Primeros y últimos registros ---")
display(df_m30.head())
display(df_m30.tail())

# 4. Detección de valores nulos explícitos
print("\n--- 3. Conteo de Valores Nulos ---")
print(df_m30.isnull().sum())

# 5. Estadísticas descriptivas para detectar anomalías (ej. intensidades negativas)
print("\n--- 4. Estadísticas Descriptivas ---")
display(df_m30.describe())

--- 1. Información General del Dataset ---
<class 'pandas.DataFrame'>
RangeIndex: 9624596 entries, 0 to 9624595
Data columns (total 6 columns):
 #   Column      Dtype
---  ------      -----
 0   id          int64
 1   fecha       datetime64[us]
 2   intensidad  float64
 3   ocupacion   float64
 4   carga       float64
 5   vmed        float64
dtypes: datetime64[us](1), float64(4), int64(1)
memory usage: 440.6 MB

==================================================

--- 2. Primeros y últimos registros ---

     id               fecha  intensidad  ocupacion  carga   vmed
0  1012 2022-01-01 00:00:00       36.00       1.00    0.0  11.00
1  1012 2022-01-01 01:00:00      509.25       4.25    0.0  53.25
2  1012 2022-01-01 02:00:00      441.00       3.75    0.0  51.00
3  1012 2022-01-01 03:00:00      144.00       0.75    0.0  50.75
4  1012 2022-01-01 04:00:00       96.00       0.50    0.0  48.25

            id               fecha  intensidad  ocupacion  carga       vmed
9624591  11486 2026-02-02 05:00:00         0.0   1.500000    0.0  68.000000
9624592  11486 2026-02-02 06:00:00         0.0  12.250000    0.0  62.250000
9624593  11486 2026-02-02 07:00:00         0.0  40.000000    0.0  24.250000
9624594  11486 2026-02-02 08:00:00         0.0  43.000000    0.0  22.250000
9624595  11486 2026-02-02 09:00:00         0.0  31.666667    0.0  29.666667

--- 3. Conteo de Valores Nulos ---
id            0
fecha         0
intensidad    0
ocupacion     0
carga         0
vmed          0
dtype: int64

--- 4. Estadísticas Descriptivas ---

,id,fecha,intensidad,ocupacion,carga,vmed
count,9.624596e+06,9624596,9.624596e+06,9.624596e+06,9.624596e+06,9.624596e+06
mean,6.471382e+03,2024-04-22 08:05:25.665744,1.365393e+03,5.948299e+00,3.327969e+01,6.766578e+01
min,1.012000e+03,2022-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.651000e+03,2023-05-25 03:00:00,3.232500e+02,1.250000e+00,7.000000e+00,5.800000e+01
50%,6.744000e+03,2024-04-28 04:00:00,8.860000e+02,4.000000e+00,2.775000e+01,7.075000e+01
75%,6.854000e+03,2025-04-01 03:00:00,2.058250e+03,7.750000e+00,5.575000e+01,8.200000e+01
max,1.148600e+04,2026-02-28 23:00:00,1.961400e+04,1.000000e+02,1.000000e+02,2.460000e+02
std,2.148000e+03,NaN,1.340418e+03,8.140489e+00,2.815250e+01,1.968082e+01

In [2]:
# Filtra y cuenta directamente
cantidad = (df_m30['intensidad'] == 0).sum()

print(f"Número de filas con intensidad 0: {cantidad}")

Número de filas con intensidad 0: 108710